version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: abcd
      MYSQL_DATABASE: db
      MYSQL_USER: charnal
      MYSQL_PASSWORD: abcd
    ports:
      - "9906:3306"
  web:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
    # TODO : lancer commande au démarrage
    # command: 
     # - " dockr-php-ext-install pdo pdo_mysql"
     # - service apache2 restart # ATTENTION SI GROS PB C'EST QUE LE CONTAINER BOOT EN BOUCLE , sinon lancer la commande dans le container

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
    - db
    external_links:
    - db:mysql
    ports:
    - "9191:80"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: abcd
      MYSQL_ROOT_PASSWORD: abcd
      PMA_HOST: db
